ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.cart_delete, name='cart_delete'),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("shop.urls")),
    path('search/', include("search_app.urls")),
    path('cart/', include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.searchResult, name='SearchResult'),
]

ecommerceproject/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail'),
]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatDetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(req):
    cart = req.session.session_key
    if not cart:
        cart = req.session.create()
    return cart

def add_cart(req, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(req))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(req))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(req, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(req))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(req, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(req, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(req))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def cart_delete(req, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(req))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(req):
    products = None
    query = None
    if 'q' in req.GET:
        query = req.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(req, 'search.html', {'query': query, 'products': products})

ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.

def allProdCat(req, c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 8)
    try:
        page = int(req.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(req, "category.html", {'category': c_page, 'products': products})

def proDetail(req, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(req, 'product.html', {'product': product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/4c7ac3f4f0.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>
        h1{
            font-weight: 700;
        }
        h4{
            font-weight: 500;
        }
        h6{
            font-weight: 400;
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100" style="font-family: 'Ubuntu'; font-size: 1.5rem;">
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Cart Page - Proceed To Review Your Items And Place The Order
{% endblock %}

{% block title %}
    Cart - ClickToCart
{% endblock %}

{% block content %}
  {% if not cart_items %}
    <div>
      <div class="text-center">
        <br>
        <h1 class="text-center">Your Shopping Cart Is Empty</h1><br>
        <p class="text-center">Please Click <a href="{% url 'shop:allProdCat' %}">Here</a> To Continue Shopping</p>
      </div>
    </div>
  {% else %}
    <div class="container-fluid">
      <div class="text-center">
        <br>
        <h1 class="text-center">Your Shopping Cart</h1><br>
      </div>
      <div class="row mx-auto">
        <div class="col-lg-8 col-md-12 text-center">
          <table class="table">
            <thead class="my_thead">
            <tr>
              <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
              <tr>
                <td>
                  <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" height="150px"></a>
                </td>
                <td class="text-start">
                  {{cart_item.product.name}}<br>
                  SKU: {{cart_item.product.id}}<br>
                  Price: ₹ {{cart_item.product.price}}<br>
                  Qty: {{cart_item.quantity}} x ₹ {{cart_item.product.price}}
                </td>
                <td>
                  ₹ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                  <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="text-decoration-none"><i class="fa-solid fa-circle-plus custom_icon"></i></a>
                  &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="text-decoration-none"><i class="fa-solid fa-circle-minus  custom_icon"></i></a>
                  <a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="text-decoration-none"><i class="fa-solid fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                  &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="text-decoration-none"><i class="fa-solid fa-circle-minus  custom_icon"></i></a>
                  &nbsp;<a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="text-decoration-none"><i class="fa-solid fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col-lg-4 col-md-12 text-center">
          <table class="table">
            <thead class="my_thead">
            <tr>
              <th>
                Checkout
              </th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>
                Please review your shopping cart items before proceeding with the order payment.
              </td>
            </tr>
            <tr>
              <td class="text-left">
                Your Total:&nbsp; <strong>₹ {{total}}</strong>
              </td>
            </tr>
            </tbody>
          </table>
          <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-primary btn-block mt-1">Continue Shopping</a>
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-success btn-block mt-1">Make Payment</a>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to Click To Cart for a nice online shopping experience...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        Click To Cart - {{ category.name }}
    {% else %}
        Click To Cart - See our new collections
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a></p>
                </div>
            </div>
        </div>
    {% endif %}

    {% if category %}
        <div class="mx-auto text-center">
            <img src="{{category.image.url}}" alt="{{category.name}}">
        </div><br>
        <div>
            <h1 class="text-center my_title">{{category.name}}</h1>
            <p class="text-center text-justify">{{category.description}}</p>
        </div>
    {% else %}
        <div>
            <img class="mt-2 my_image p-1" src="{% static 'img/banner.png' %}" alt="our products" width="1500px">
        </div><br>
        <div>
            <h1 class="text-center my_title">Our Product Collections</h1>
            <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClinton, a Latin professor at Hampered-Sydney College in Virginia, looked up one of the more obscure Latin words, consecrate, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubted source.</p>
        </div>
    {% endif %}
    <div class="container">
        <div class="row">
            {% for product in products.object_list %}
            <div class="col-md-3 col-sm-12 mb-3">
                <div class="card">

                    <img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}" height="350px">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <h6 class="card-text">Price: ₹{{product.price}}</h6>
                        <a href="{{product.get_url}}" class="btn btn-primary">View Product</a>
                        <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-success">Add To Cart</a>
                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-secondary btn-sm mb-3 {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

<!--    <div>-->
<!--        <div>-->
<!--            {% for product in products %}-->
<!--                <div class="container">-->
<!--                    <div class="row">-->
<!--                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>-->
<!--                    </div>-->
<!--                    <div>-->
<!--                        <h4>{{product.name}}</h4>-->
<!--                        <h6>{{product.price}}</h6>-->
<!--                    </div>-->
<!--                </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer mt-auto">
  <p class="text-center"><strong>&copy; ClickToCart. All rights reserved.</strong></p>
</div>

ecommerceproject/templates/header.html
<!--{% load static %}-->
<!--<header>-->
<!--  <p style="text-align:center;">-->
<!--    <a href="{% url 'shop:allProdCat' %}"><img class="mt-3" src="{% static 'img/logo.png' %}" alt="logo" width="100px" height="100px"></a>-->
<!--  </p>-->
<!--</header>-->

ecommerceproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logo" width="50px" height="50px"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 ms-3 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping fs-4"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-info" type="submit"><i class="fa-solid fa-magnifying-glass text-white"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

  {{ product.description|truncatewords:155 }}

{% endblock %}

{% block title %}
  {% if category %}
    {{ product.name }} - Click To Cart
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row pt-4 pb-2">
    <div>
      <p><a class="text-decoration-none" href="{% url 'shop:allProdCat' %}">Home</a> | <a class="text-decoration-none" href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
  </div>
  <br>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12">
      <img src="{{product.image.url}}" alt="{{product.name}}" height="350px" width="350px">
    </div>
    <div class="col-lg-6 col-md-12 col-sm-12">
      <h4 class="text-uppercase my_prod_title">{{product.name}}</h4><hr>
      <h5>₹{{product.price}}</h5><hr>
      <h5><u>Product Description:</u></h5>
      <p class="fs-6">{{product.description}}</p><hr>
      {% if product.stock <= 0 %}
        <p><strong>Out Of Stock</strong></p>
      {% else %}
        <a class="btn btn-success mb-3" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to Click To Cart for a nice online shopping experience...
{% endblock %}

{% block title %}
    Search Page
{% endblock %}

{% block content %}
    <div>
        <p class="text-center pt-4">You have searched for: <b>"{{query}}"</b></p>
    </div>
<div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-3 col-sm-12 mb-3">
                <div class="card">

                    <img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}" height="250px">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <h6 class="card-text">Price: ₹{{product.price}}</h6>
                        <a href="{{product.get_url}}" class="btn btn-primary">View Product</a>
                    </div>

                </div>
            </div>

            {% empty %}
                <div class="row mx-auto">
                    <p class="text-center pt-4">0 results found</p>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}